baseurl = "/"
title = "dnsproblem.dev?"
theme = "hugo-coder"
canonifyurls = true
hasCJKLanguage = true

[taxonomies]
  series = "series"

[params]
    author = "Of course it is a dns problem!"
    avatar = "avatar.jpg"
    favicon = "favicon.ico"
    description = "dnsproblem.dev"
    publicationYear = "2021"

[outputs]
    section = ["JSON", "HTML"]

[[menu.main]]
    identifier = "twitter"
    # name = "Twitter"
    pre = "<i class='fab fa-twitter fa-lg'></i>"
    url = "https://twitter.com/problemDNS"
    weight = 20

